"""Company branding.

The suite is white-labelled: the operator's own identity appears on the window,
the job cards the shop floor reads, the quotations customers receive and the
headers of generated machine code. All of it comes from one :class:`Brand`,
loadable as a hot-reloadable data plugin (``kind: "brand"``) so a company can
change its own details without a software release.

Only facts belong here. Fields the operator has not supplied are left empty and
simply do not render, rather than being filled with plausible-looking
placeholder text that could end up on a customer's quotation.
"""

from __future__ import annotations

from typing import Any

from pydantic import BaseModel, ConfigDict, Field

from .core.hotreload import DataSchema
from .core.registry import Registry

#: Brands are hot-reloadable like every other catalogue.
BRANDS: Registry[Any] = Registry("brands")


class BrandColours(BaseModel):
    """Accent colours applied to the interface and printed documents."""

    model_config = ConfigDict(extra="forbid")

    accent: str = "#3d8bfd"
    accent_light: str = "#0b62d0"
    #: Used on documents; defaults to the accent when unset.
    document: str | None = None

    def document_colour(self) -> str:
        return self.document or self.accent_light


class Brand(BaseModel):
    """The identity shown throughout the application and its documents."""

    model_config = ConfigDict(extra="forbid")

    id: str = "profileos"
    kind: str = "brand"
    version: str = "1.0"

    #: Trading name, shown in the interface.
    name: str = "ProfileOS"
    #: Registered legal name, used on quotations and contracts.
    legal_name: str | None = None
    tagline: str | None = None

    # -- contact, all optional: an empty field is omitted, never invented ----
    address_line: str | None = None
    city: str | None = None
    postcode: str | None = None
    country: str | None = None
    phone: str | None = None
    fax: str | None = None
    email: str | None = None
    website: str | None = None
    #: Company registration / VAT number printed on quotations.
    registration_number: str | None = None

    colours: BrandColours = Field(default_factory=BrandColours)
    #: Emitted into NC file headers, so a program is traceable to its origin.
    machine_code_signature: str | None = None
    notes: str | None = None

    # -- rendering ------------------------------------------------------------ #
    @property
    def display_name(self) -> str:
        return self.name

    @property
    def document_name(self) -> str:
        """The name to print on a customer-facing document."""
        return self.legal_name or self.name

    def address_lines(self) -> list[str]:
        """Address as printable lines, omitting anything not supplied."""
        lines: list[str] = []
        if self.address_line:
            lines.append(self.address_line)
        locality = " ".join(part for part in (self.city, self.postcode) if part)
        if locality:
            lines.append(locality)
        if self.country:
            lines.append(self.country)
        return lines

    def contact_lines(self) -> list[str]:
        """Contact details as printable lines, labelled."""
        lines: list[str] = []
        if self.phone:
            lines.append(f"Tel {self.phone}")
        if self.fax:
            lines.append(f"Fax {self.fax}")
        if self.email:
            lines.append(self.email)
        if self.website:
            lines.append(self.website)
        return lines

    def letterhead(self) -> list[str]:
        """Every line of a document letterhead, in order."""
        lines = [self.document_name]
        if self.tagline:
            lines.append(self.tagline)
        lines.extend(self.address_lines())
        lines.extend(self.contact_lines())
        if self.registration_number:
            lines.append(f"Reg. {self.registration_number}")
        return lines

    def nc_header(self) -> str:
        """One-line provenance stamp for generated machine code."""
        return self.machine_code_signature or f"{self.name} - generated by ProfileOS"

    def window_title(self, suffix: str = "") -> str:
        base = f"{self.name} — ProfileOS" if self.name != "ProfileOS" else "ProfileOS"
        return f"{base} — {suffix}" if suffix else base


#: The default, unbranded identity.
DEFAULT_BRAND = Brand()

#: Configured operator.
#:
#: Details verified from public business directory listings (Dapey Zahav /
#: B144 / DunsGuide, August 2026). Fields not confirmed by those listings are
#: deliberately left unset rather than guessed — fill them in from the
#: company's own records, or by editing the brand plugin, which needs no
#: software release.
DADI_BRAND = Brand(
    id="dadi",
    name='דאדי בע"מ',
    legal_name='דאדי בע"מ',
    tagline="אלומיניום לבניין",
    address_line="סולם יעקב 1",
    city="בית אל",
    postcode="9063100",
    country="ישראל",
    phone="02-9973510",
    fax="02-9973159",
    colours=BrandColours(accent="#3d8bfd", accent_light="#0b62d0"),
    machine_code_signature='דאדי בע"מ - ProfileOS',
    notes=(
        "Contact details taken from public business-directory listings. "
        "Email, website and registration number are not set because they were "
        "not confirmed there; add them in the brand plugin."
    ),
)

#: Brands shipped with the application.
BUILTIN_BRANDS: dict[str, Brand] = {
    DEFAULT_BRAND.id: DEFAULT_BRAND,
    DADI_BRAND.id: DADI_BRAND,
}

#: Set by :func:`set_active_brand` for the life of the process. ``None`` means
#: no in-process override, so the persisted setting decides.
_active_brand_id: str | None = None


def configured_brand_id() -> str:
    """The brand this installation is set to, from settings unless overridden."""
    if _active_brand_id is not None:
        return _active_brand_id
    try:
        from .core.config import get_settings

        return (get_settings().brand_id or "profileos").strip().lower()
    except Exception:  # noqa: BLE001 - branding must never break on settings
        return "profileos"


def get_brand(brand_id: str | None = None) -> Brand:
    """Return a brand, preferring registry (plugin) entries over built-ins."""
    key = (brand_id or configured_brand_id()).strip().lower()
    registered = BRANDS.get_or_none(key)
    if isinstance(registered, Brand):
        return registered
    return BUILTIN_BRANDS.get(key, DEFAULT_BRAND)


def set_active_brand(brand_id: str, *, persist: bool = False) -> Brand:
    """Choose which brand the application presents.

    ``persist`` writes the choice to settings, so the next launch — and the
    machine programs it posts — carry the same operator.
    """
    global _active_brand_id
    _active_brand_id = brand_id.strip().lower()
    if persist:
        from .core.config import get_settings, save_settings

        settings = get_settings()
        settings.brand_id = _active_brand_id
        save_settings(settings)
    return get_brand()


def active_brand() -> Brand:
    return get_brand()


def register_brand(brand: Brand) -> None:
    BRANDS.add(brand.id, brand, version=brand.version, source="api")


def _validate_brand(document: dict[str, Any]) -> Brand:
    return Brand.model_validate(document)


#: Registers ``kind: "brand"`` documents as hot-reloadable plugins.
BRAND_SCHEMA = DataSchema(
    kind="brand",
    model=_validate_brand,
    registry=BRANDS,
    key_field="id",
    document_model=Brand,
)


__all__ = [
    "BrandColours",
    "Brand",
    "DEFAULT_BRAND",
    "DADI_BRAND",
    "BUILTIN_BRANDS",
    "BRANDS",
    "BRAND_SCHEMA",
    "get_brand",
    "set_active_brand",
    "configured_brand_id",
    "active_brand",
    "register_brand",
]
